version: "2"
services:
  plex-cloud-suite:
    build: .
    cap_add:
      - MKNOD
    command: supervisor.sh
    image: 'mrmachine/plex-cloud-suite:local'
    ports:
      - '80:80'
      - '443:443'
      - '51413:51413'
      - '51413:51413/udp'
    privileged: true
    restart: always
    volumes:
      - ./bin:/opt/bin
      - ./etc:/opt/etc
      - ./local:/mnt/local
      - ./var:/opt/var
