version: "2"
services:
  couchpotatoserver:
    environment:
      NZBS_ORG_API_KEY:
      PASSTHEPOPCORN_PASSWORD:
      PASSTHEPOPCORN_PASSKEY:
      PLEX_PASSWORD:
      PLEX_USERNAME:
      PUSHOVER_USER_KEY:
  nzbget:
    environment:
      SERVER1_USERNAME:
      SERVER1_PASSWORD:
  sickrage:
    environment:
      BTN_API_KEY:
      NZBS_ORG_API_KEY:
      PLEX_PASSWORD:
      PLEX_USERNAME:
      PUSHOVER_API_KEY:
      PUSHOVER_USER_KEY:
