version: "2"
services:
  letsencrypt:
    build: letsencrypt
    image: mrmachine/letsencrypt:latest
    ports:
      - '80:80'
    restart: always
  plex-cloud-encfs:
    build: .
    cap_add:
      - MKNOD
    command: supervisor.sh
    image: 'mrmachine/plex-cloud-encfs:latest'
    ports:
      - '443:443'
      - '32400:32400'
      - '51413:51413'
    privileged: true
    restart: always
    volumes:
      - ./bin:/opt/bin
      - ./etc:/opt/etc
      - ./local-storage:/mnt/local-storage
      - ./var:/opt/var
    volumes_from:
      - letsencrypt
